plugins:
  pylint:
    enabled: true
    checks:
      import-error:
        enabled: false
      logging-format-interpolation:
        enabled: false
      import-outside-toplevel:
        enabled: false
      bad-continuation:
        enabled: false
      method-count:
        config:
          threshold: 25